#!/usr/bin/env bash

# Build project for production


## Check if server/.env is setup correctly for production build

if [ ! -f "server/.env" ]; then
    echo "ERROR: No .env file found in server/"

    ### Ask if user wants to create a new .env file
    read -p "Do you want to create a new .env file? (y/n): " create_new_env
    if [ "$create_new_env" == "y" ]; then
        cp server/.env.production.sample server/.env
    else
        echo "Please ensure that .env is setup correctly for production build."
        exit 1
    fi
fi

if grep -q "DEBUG=True" server/.env; then
    echo "ERROR: DEBUG is set to True in server/.env"
    echo "Please ensure that .env is setup correctly for production build."
    exit 1
fi


## Build Backend

source venv/bin/activate
cd server
python manage.py migrate
python manage.py collectstatic --noinput
deactivate
cd - >/dev/null


## Build Frontend

STATIC_APP_DIR="server/static/app"

### Build frontend files and move to static app dir
cd app
npm run build
cd - >/dev/null

rm -rf "$STATIC_APP_DIR"
mv app/dist "$STATIC_APP_DIR"


### Setup server's website dist index.html template
WEBSITE_TEMPLATE_DIST_DIR="server/apps/website/templates/website/dist"
mkdir -p "$WEBSITE_TEMPLATE_DIST_DIR"
cp -p "$STATIC_APP_DIR/index.html" "$WEBSITE_TEMPLATE_DIST_DIR/index.html"

### Update path to static files referenced in dist/index.html

# get_sed_command() {
#     # Determine which sed to use (use gsed on macOS)
#     if [[ "$(uname)" == "Darwin" ]]; then
#         if command -v gsed &>/dev/null; then
#             echo "gsed"
#         else
#             echo "Error: gsed is required on macOS. Please install it with: brew install gnu-sed" >&2
#             exit 1
#         fi
#     else
#         echo "sed"
#     fi
# }
# SED_CMD=$(get_sed_command)

# $SED_CMD -i 's|src="/|src="/static/app/|g' "$WEBSITE_TEMPLATE_DIST_DIR/index.html"
# $SED_CMD -i 's|href="/|href="/static/app/|g' "$WEBSITE_TEMPLATE_DIST_DIR/index.html"
