#!/usr/bin/env bash

# Build project for production


## Check if server/.env is setup correctly for production build

if [ ! -f "server/.env" ]; then
    echo "ERROR: No .env file found in server/"

    ### Ask if user wants to create a new .env file
    read -p "Do you want to create a new .env file? (y/n): " create_new_env
    if [ "$create_new_env" == "y" ]; then
        cp server/.env.production.sample server/.env
    else
        echo "Please ensure that .env is setup correctly for production build."
        exit 1
    fi
fi

if grep -q "DEBUG=True" server/.env; then
    echo "ERROR: DEBUG is set to True in server/.env"
    echo "Please ensure that .env is setup correctly for production build."
    exit 1
fi


## Build Backend

source venv/bin/activate
cd server
python manage.py migrate
python manage.py collectstatic --noinput
deactivate
cd - >/dev/null


## Build Frontend

STATIC_APP_DIR="server/static/app"

### Build frontend files and move to static app dir
cd app
npm run build
cd - >/dev/null

rm -rf "$STATIC_APP_DIR"
mv app/dist "$STATIC_APP_DIR"


### Setup server's website dist index.html template
WEBSITE_TEMPLATE_DIST_DIR="server/apps/website/templates/website/dist"
mkdir -p "$WEBSITE_TEMPLATE_DIST_DIR"
cp -p "$STATIC_APP_DIR/index.html" "$WEBSITE_TEMPLATE_DIST_DIR/index.html"
