#!/usr/bin/env bash

# Build project for production


## Build Backend

manage() {
	venv/bin/python server/manage.py $@ --settings=config.settings_production
}

manage migrate
manage collectstatic --noinput


## Build Frontend

STATIC_APP_DIR="server/static/app"

### Build frontend files and move to static app dir
cd app
npm run build
cd - >/dev/null

rm -rf "$STATIC_APP_DIR"
mv app/dist "$STATIC_APP_DIR"


### Setup server's website dist index.html template
WEBSITE_TEMPLATE_DIST_DIR="server/apps/website/templates/website/dist"
mkdir -p "$WEBSITE_TEMPLATE_DIST_DIR"
cp -p "$STATIC_APP_DIR/index.html" "$WEBSITE_TEMPLATE_DIST_DIR/index.html"

### Update path to static files referenced in dist/index.html

get_sed_command() {
	# Determine which sed to use (use gsed on macOS)
    if [[ "$(uname)" == "Darwin" ]]; then
        if command -v gsed &>/dev/null; then
            echo "gsed"
        else
            echo "Error: gsed is required on macOS. Please install it with: brew install gnu-sed" >&2
            exit 1
        fi
    else
        echo "sed"
    fi
}
SED_CMD=$(get_sed_command)

$SED_CMD -i 's|src="/|src="/static/app/|g' "$WEBSITE_TEMPLATE_DIST_DIR/index.html"
$SED_CMD -i 's|href="/|href="/static/app/|g' "$WEBSITE_TEMPLATE_DIST_DIR/index.html"