"""Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.2.

Note: The doc reference URLs to djangoproject.com in project have been updated
to reflect the latest version of Django used in the project--currently 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import copy
import logging
import logging.config
import os
from pathlib import Path

from csp.constants import SELF
from django.utils.log import DEFAULT_LOGGING
from environs import Env

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'server': {  # Main app logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'server.apps': {  # Apps logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,  # Prevent propagation to avoid duplicate logs
        },
        'django': {  # Django framework logger
            'handlers': ['console'],
            'level': 'INFO',  # Set to INFO to reduce noise
            'propagate': True,
        },
    },
}

# Initialize logging
logging.config.dictConfig(LOGGING)
logger = logging.getLogger('server')

# Environment variables
# Reference: https://github.com/sloria/environs
env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def check_and_create_env_file():
    """Create a default .env file for local or production-like startup."""
    # NOTE: In production containers and gunicorn, the working directory is
    # the server project root. During local development from the repo root,
    # the server child directory is present.
    is_server_child_dir_present = (Path.cwd() / 'server').exists()
    if is_server_child_dir_present:
        env_file = 'server/.env'
    else:
        env_file = '.env'

    if not Path(env_file).is_file():
        logger.debug('Required .env file not found.')
        from django.core.management.utils import get_random_secret_key

        with open(env_file, 'a') as f:
            f.write('SECRET_KEY=' + get_random_secret_key() + '\n')
            if is_server_child_dir_present:
                f.write('DEBUG=True\n')
                f.write('DATABASE_URL=sqlite:///server/db.sqlite3\n')
                f.write('USE_LOCAL_FILE_STORAGE=True\n')
                f.write('MEDIA_ROOT=server/uploads\n')
                logger.debug(
                    'Created .env file at server/.env with default values for development.'
                )
                logger.warning('Please edit the .env file for production environment.')
            else:
                f.write('DEBUG=False\n')
                f.write('DATABASE_URL=sqlite:////data/db.sqlite3\n')
                f.write('MEDIA_ROOT=/data/uploads\n')
                logger.debug('Created .env file at .env with default values for production.')
        logger.debug('')


check_and_create_env_file()

env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start settings
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# Also https://fly.io/django-beats/deploying-django-to-production/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

FLY_APP_NAME = env('FLY_APP_NAME', default='')

if not DEBUG:
    ALLOWED_HOSTS = []
    if FLY_APP_NAME:
        ALLOWED_HOSTS.append(f'{FLY_APP_NAME}.fly.dev')
    ALLOWED_HOSTS += [
        '127.0.0.1',
        'localhost',
        'webframework.fly.dev',
        'webframework.dev',
        'wut.sh',
        'www.wut.sh',
    ]

    # HTTPS hardening for production behind the Fly proxy.
    # Fly terminates TLS at the edge and forwards the original scheme in
    # X-Forwarded-Proto; without this, request.is_secure() is always False
    # behind the proxy, so Secure cookies and HSTS would never apply.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HTTP->HTTPS redirection is handled at the edge (force_https in fly.toml),
    # so SECURE_SSL_REDIRECT stays off and internal health checks keep working.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The frontend reads the CSRF token from /auth/csrf/, not from the cookie.
    CSRF_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days; raise once proven stable

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    #
    # third-party apps
    'rest_framework',
    'corsheaders',
    'django_extensions',
    'django_tasks',
    'django_tasks_db',
    #
    # project apps
    'apps.users.apps.UsersConfig',
    'apps.website',
    'apps.blogs',
]

MIDDLEWARE = [
    # Must stay first so platform health checks bypass host validation.
    'config.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.dj_db_url('DATABASE_URL', default='sqlite:///db.sqlite3')
    or {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    # The db_worker process polls and claims tasks in the same SQLite file;
    # WAL + busy timeout prevent "database is locked" errors.
    sqlite_options = DATABASES['default'].setdefault('OPTIONS', {})
    sqlite_options.setdefault(
        'init_command', 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;'
    )
    sqlite_options.setdefault('transaction_mode', 'IMMEDIATE')
    sqlite_options.setdefault('timeout', 20)

if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    # Persistent, health-checked connections; the managed Postgres is a
    # network hop away and per-request reconnects are expensive.
    DATABASES['default']['CONN_MAX_AGE'] = env.int('DB_CONN_MAX_AGE', default=60)
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Caches
#
# Django's implicit default is LocMemCache with MAX_ENTRIES=300: once a cache
# holds more than 300 keys it culls a third of them at random. Throttle counters
# live in a cache, so sharing one with general-purpose caching means a burst of
# unrelated writes can evict a counter mid-window and silently disable rate
# limiting exactly when traffic is highest. Hence two caches:
#
#   default   — general use, and DRF's throttles (SimpleRateThrottle is hardwired
#               to this alias). Raised ceiling so throttle state is not culled.
#   ratelimit — counters for apps.ratelimit, isolated from everything else.
#
# LocMemCache is per process, so with multiple gunicorn workers these limits are
# per worker and approximate. Point both at Redis/Memcached if a hard global
# guarantee is ever needed.
#
# The two ceilings differ because the entries cost wildly different amounts.
# LocMemCache stores pickled values, and:
#
#   default   — DRF's SimpleRateThrottle stores a *list of request timestamps*
#               per key, up to num_requests long (1000/hour for 'user',
#               300/hour for 'anon'). That is ~2.7-9 kB per key, so 10k keys is
#               ~27-90 MB per worker; start-prod.sh runs 2 workers on a 512 MB
#               VM. Culling below that is the lesser evil, and reaching 10k
#               distinct clients an hour is the point at which the honest fix is
#               a shared cache backend rather than a bigger ceiling.
#   ratelimit — apps.ratelimit stores a single int per key, tens of bytes, so a
#               high ceiling is nearly free and buys real eviction headroom.
_DEFAULT_CACHE_MAX_ENTRIES = env.int('CACHE_MAX_ENTRIES', default=10_000)
_RATE_LIMIT_CACHE_MAX_ENTRIES = env.int('RATE_LIMIT_CACHE_MAX_ENTRIES', default=50_000)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'default',
        'OPTIONS': {'MAX_ENTRIES': _DEFAULT_CACHE_MAX_ENTRIES},
    },
    'ratelimit': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ratelimit',
        'OPTIONS': {'MAX_ENTRIES': _RATE_LIMIT_CACHE_MAX_ENTRIES},
    },
}


# Test runner: pins media storage to the filesystem so `manage.py test` behaves the
# same whatever a developer's server/.env says about S3/R2. See config/test_runner.py.
TEST_RUNNER = 'config.test_runner.LocalStorageTestRunner'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 16,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

SERVER_PATH = Path.cwd()
IS_SERVER_CHILD_DIR_PRESENT = (Path.cwd() / 'server').exists()
if IS_SERVER_CHILD_DIR_PRESENT:
    SERVER_PATH = SERVER_PATH / 'server'

STATIC_ROOT = SERVER_PATH / 'static'
STATIC_URL = '/static/'

if DEBUG:
    # Include static files from app/public directory during development
    # Reference: https://docs.djangoproject.com/en/5.1/ref/settings/#staticfiles-dirs
    STATICFILES_DIRS = [SERVER_PATH / '..' / 'app' / 'public']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/

LOGGING = copy.deepcopy(DEFAULT_LOGGING)


def setup_save_errorlog_to_file(logging: dict):
    """Configure server error logging to a rotating file."""
    import os

    log_dir: Path = BASE_DIR / '..' / 'log'
    errorlog_filepath: Path = log_dir / 'server-errors.log'

    def create_log_dir_for_server_errors():
        if not log_dir.exists():
            os.mkdir(log_dir)
        if not errorlog_filepath.exists():
            with open(errorlog_filepath, 'w'):
                pass

    create_log_dir_for_server_errors()

    # if not DEBUG:
    #     # In case of a single server managing multiple apps, symlink the
    #     # project's server error log to the common /var/log/app-errors directory.
    #     def symlink_error_log_in_system_logs():
    #         log_symlinkpath: str = f'/var/log/app-errors/{BASE_DIR.parent.name}.log'
    #         if not Path(log_symlinkpath).parent.exists():
    #             import subprocess

    #             subprocess.call('./sys/mkdir-error-log')
    #             # subprocess.call(BASE_DIR / '..' / 'sys/mkdir-error-log')
    #         if not Path(log_symlinkpath).is_symlink():
    #             os.symlink(errorlog_filepath, log_symlinkpath)

    #     try:
    #         symlink_error_log_in_system_logs()
    #     except FileNotFoundError as e:
    #         print(e)

    logging['formatters'].update(
        {
            # DEFAULT_LOGGING only ships `django.server` ([time] message), which
            # names neither the level nor the module — fine for request lines,
            # too thin for an error log you read after the fact. `{name}` is the
            # dotted logger name (apps.blogs.views), not `{module}`, which would
            # render both blogs/views.py and users/views.py as bare `views`.
            'app': {
                'format': '{levelname} {asctime} {name} {message}',
                'style': '{',
            },
        }
    )
    logging['handlers'].update(
        {
            'file_errors': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'formatter': 'app',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': errorlog_filepath,
                'maxBytes': 10485760,  # 10MB
                'backupCount': 5,
            },
            # DEFAULT_LOGGING's `console` carries a require_debug_true filter, so
            # under DEBUG=False it drops every record — which would leave
            # `file_errors` as the only destination in production, and that file
            # lives on the container's ephemeral filesystem (BASE_DIR/../log,
            # i.e. /log in the image), not on the mounted volume. It is wiped on
            # every deploy and never reaches `fly logs`. This unfiltered twin
            # keeps app errors on stderr in both modes, which is what Fly's log
            # stream actually captures.
            #
            # Level INFO, matching `console`: the app loggers sit at DEBUG so a
            # module *can* opt into debug output locally, but debug records must
            # not reach production stderr — blogs/transcription.py logs whole
            # transcripts at that level.
            'app_console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'app',
            },
            # The stderr twin of `file_errors` — same level, same filter, so it
            # fires exactly when that one does. Django's own errors (the
            # `django.request` ERROR carrying an unhandled 500's traceback,
            # django.security.*) otherwise share the fate the app loggers just
            # escaped: filtered out of `console` under DEBUG=False and left only
            # in the ephemeral log file. `django` cannot simply move to
            # `app_console` the way the app loggers did — at INFO it would put a
            # django.request WARNING on stderr for every 404, which on a public
            # site is bot noise, not signal. Restricting this to ERROR takes the
            # tracebacks and leaves the scan traffic behind. require_debug_false
            # keeps development output identical: `console` alone, no duplicates.
            'console_errors': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': 'logging.StreamHandler',
                'formatter': 'app',
            },
        }
    )
    logging['loggers'].update(
        {
            'django': {
                'handlers': ['console', 'console_errors', 'file_errors'],
                'level': 'INFO',
                'propagate': True,
            },
            'server': {
                'handlers': ['app_console', 'file_errors'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'server.apps': {
                'handlers': ['app_console', 'file_errors'],
                'level': 'DEBUG',
                'propagate': False,
            },
            # Same config under the other prefix app modules actually log to.
            # server/ is the import root, so a module at server/apps/blogs/views.py
            # is imported as `apps.blogs.views` — `logging.getLogger(__name__)`
            # there resolves to `apps`, not `server.apps`, and inherits root: no
            # handlers and an effective level of WARNING. Its debug/info calls are
            # dropped and its exceptions fall through to logging.lastResort, which
            # writes bare stderr and never reaches file_errors. Configuring both
            # prefixes means either convention lands in the error log; see
            # apps/blogs/tests/test_logging.py, which fails if a logger stops
            # resolving to a handler.
            'apps': {
                'handlers': ['app_console', 'file_errors'],
                'level': 'DEBUG',
                'propagate': False,
            },
        }
    )
    return logging


LOGGING = setup_save_errorlog_to_file(LOGGING)


# User Model
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/
AUTH_USER_MODEL = 'users.User'


# REST Framework
# https://www.django-rest-framework.org/#example
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # Baseline abuse protection. Counters live in the default (local-memory)
    # cache, so rates are per process and approximate — good enough to blunt
    # bulk abuse, not a hard global guarantee. The IP-keyed throttles identify a
    # client by Fly's trusted `Fly-Client-IP` header (see apps/throttling.py), so
    # a rotated `X-Forwarded-For` can no longer mint a fresh bucket per request.
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.throttling.IpAnonRateThrottle',
        'apps.throttling.IpUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/hour',
        'user': '1000/hour',
        'transcribe': '10/hour',
        'views': '120/min',
    },
    # Defense in depth for any throttle that still uses DRF's default get_ident:
    # Fly is the single proxy hop, so trust exactly one X-Forwarded-For entry.
    'NUM_PROXIES': 1,
}

# Background tasks (django-tasks, a backport of Django 6's django.tasks).
# Dev and CI run tasks inline so no worker process is needed; production uses
# the database backend, drained by `manage.py db_worker` (see server/start-prod.sh).
TASKS_IMMEDIATE = env.bool('TASKS_IMMEDIATE', default=DEBUG)
TASKS = {
    'default': {
        'BACKEND': (
            'django_tasks.backends.immediate.ImmediateBackend'
            if TASKS_IMMEDIATE
            else 'django_tasks_db.DatabaseBackend'
        ),
    }
}

# Handle server headers required for Cross-Origin Resource Sharing (CORS)
# https://pypi.org/project/django-cors-headers/
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    # 'http://localhost:8080',
]
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            'http://localhost:3000',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ]
    )

CSRF_TRUSTED_ORIGINS = []
if FLY_APP_NAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{FLY_APP_NAME}.fly.dev')
CSRF_TRUSTED_ORIGINS += [
    'https://webframework.fly.dev',
    'https://webframework.dev',
    'https://wut.sh',
    'https://www.wut.sh',
]

# Set debug value in templates
# https://stackoverflow.com/questions/1271631/how-to-check-the-template-debug-flag-in-a-django-template
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']


# File storage configuration
# Read via the environs `env` (not os.getenv): environs>=15 loads .env values
# into the Env instance rather than os.environ, so os.getenv no longer sees them.
USE_LOCAL_FILE_STORAGE = env.bool('USE_LOCAL_FILE_STORAGE', False)

# S3-compatible object storage configuration
AWS_ACCESS_KEY_ID = env.str('R2_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env.str('R2_SECRET_ACCESS_KEY', default=None)
R2_ACCOUNT_ID = env.str('R2_ACCOUNT_ID', default=None)
R2_ENDPOINT_DOMAIN = env.str('R2_ENDPOINT_DOMAIN', default='r2.cloudflarestorage.com')
# None when the account id is unset, rather than the string 'https://None.None'.
# Note that None is *not* inert to boto3: it means "use the real AWS endpoints",
# and a None access key means "use the ambient credential chain". The check that
# turns a half-configured deployment into an error rather than a request signed
# against s3.amazonaws.com therefore lives at the point of use — not here, where
# raising would break local dev and the CI test job, which legitimately run with
# no R2 configuration at all. Both entry points are covered: apps/uploads/s3.py
# for the presign/head/delete helpers, and S3_MEDIA_STORAGE_BACKEND below for
# everything Django saves through its own storage API.
AWS_S3_ENDPOINT_URL = f'https://{R2_ACCOUNT_ID}.{R2_ENDPOINT_DOMAIN}' if R2_ACCOUNT_ID else None
AWS_STORAGE_BUCKET_NAME = env.str('R2_BUCKET_NAME', default=None)
AWS_S3_REGION_NAME = 'auto'  # R2 doesn't need a specific region
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False  # Don't add complex authentication-related query parameters to URLs
AWS_S3_ENDPOINT_FOR_CSP = env.str('R2_ENDPOINT_DOMAIN_FOR_CSP', default=None)
SENTRY_FRONTEND_INGEST_FOR_CSP = env.str('SENTRY_FRONTEND_INGEST_FOR_CSP', default=None)

# Media files configuration
MEDIA_URL = env.str('MEDIA_URL', default='/media/')
MEDIA_ROOT = env.str('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'uploads'))
MAX_MEDIA_UPLOAD_BYTES = 100 * 1024 * 1024

# Storage backend configuration
# Not plain S3Boto3Storage: the subclass adds the half-configured-R2 check that
# django-storages skips by reading the AWS_* settings itself. Keep it that way —
# swapping it back silently restores the AWS fallback for every Django-side save.
S3_MEDIA_STORAGE_BACKEND = 'apps.uploads.storage.GuardedS3Boto3Storage'
STORAGES = {
    # https://whitenoise.readthedocs.io/en/stable/django.html
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    'default': {
        'BACKEND': (
            'django.core.files.storage.FileSystemStorage'
            if USE_LOCAL_FILE_STORAGE
            else S3_MEDIA_STORAGE_BACKEND
        ),
    },
}

# Create uploads directory if using local storage
if USE_LOCAL_FILE_STORAGE and not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)


# CSP settings
# Reference: https://django-csp.readthedocs.io/en/latest/configuration.html

CONTENT_SECURITY_POLICY_DIRECTIVES = {
    'default-src': [SELF],
    'frame-ancestors': [SELF],
    'frame-src': [SELF, 'https://www.youtube-nocookie.com'],
    'form-action': [SELF],
    # No 'report-uri': /csp-report/ had no view, so the SPA catch-all took the POST
    # and CSRF rejected it. Re-add only with a real endpoint, or Sentry's ingest.
    #
    'media-src': [SELF, 'blob:'],
    'img-src': [SELF, 'blob:'],
}

if DEBUG:
    from csp.constants import UNSAFE_INLINE

    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'script-src': [SELF, UNSAFE_INLINE],
            'script-src-elem': [
                SELF,
                UNSAFE_INLINE,
                'localhost:5173',
            ],
            'style-src': [SELF, UNSAFE_INLINE, 'http://localhost:5173/src/index.css'],
            'style-src-elem': [
                SELF,
                UNSAFE_INLINE,
                'http://localhost:5173/src/index.css',
            ],
            'connect-src': [SELF, 'http://localhost:8000', 'ws://localhost:5173'],
            'media-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('media-src', []),
                'https://citizen-dj.labs.loc.gov/audio/samplepacks/loc-fma/Mushrooms_fma-178531_001_00-00-01.mp3',
                'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            ],
            'img-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('img-src', []),
                'localhost:5173',
                'https://ui-avatars.com/api/',
            ],
        }
    )
else:
    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'script-src': [
                SELF,
                # Anti-FOUC theme script in app/index.html, which builds into the shell
                # this branch serves (website/dist/index.html). Recompute when that
                # script changes -- test_csp_hashes.py enforces it.
                "'sha256-vX/WPm+OPB5oEGTIOc/PEDwUw1rNsn80bG2B5D8C9Fo='",
                #
                # Hashes for scripts in Django HTML templates
                "'sha256-DjsUj0pC5ySPg95mtQ6lmWjVIWW5WZ6Kta+NTTdw6FM='",
                "'sha256-dgKyP2HOH8aNvrK/3rkHdsaYbRTvken4D1lw/+6zP7c='",
            ],
            'style-src': [
                SELF,
                "'sha256-3FCgTKTk3allIr51SmmUMsCl5xih+z//3swOXTPQq6o='",
                "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
                "'sha256-7lAG9nNPimWNBky6j9qnn0jfFzu5wK96KOj/UzoG0hg='",
                "'sha256-CIxDM5jnsGiKqXs2v7NKCY5MzdR9gu6TtiMJrDw29AY='",
                "'sha256-9yCaDE0ZqnMqIHIqv/lrx+VJOh16ZKpxkH4PoBNWe2s='",
                "'sha256-nzTgYzXYDNe6BAHiiI7NNlfK8n/auuOAhh2t92YvuXo='",
                #
                # Hashes for styles in Django HTML templates
                "'sha256-GWweojyzwwt2WuqsMmaOTzMtCkOvLHnP8sc9dK1mDVo='",  # shared/base.html
                "'sha256-IRlJG500ORUkBOhtvOMpg7SkjvGWHfulUZyeuTyhpVE='",  # blogs/post_detail.html
                "'sha256-c2svKMHHIytNvecMVUzr4RNy61AT1b0sYT937DFULOk='",  # shared/header.html
            ],
            'connect-src': [SELF, 'http://127.0.0.1:8000'],
        }
    )

if AWS_S3_ENDPOINT_FOR_CSP:
    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'connect-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('connect-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
            'media-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('media-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
            # Signed R2 URLs are used directly as <img src> for image posts.
            'img-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('img-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
        }
    )

# The browser Sentry SDK posts events directly to the ingest host, which CSP
# must allow (e.g. 'https://o12345.ingest.us.sentry.io').
if SENTRY_FRONTEND_INGEST_FOR_CSP:
    CONTENT_SECURITY_POLICY_DIRECTIVES['connect-src'] = [
        *CONTENT_SECURITY_POLICY_DIRECTIVES.get('connect-src', []),
        SENTRY_FRONTEND_INGEST_FOR_CSP,
    ]

CONTENT_SECURITY_POLICY = {
    # 'EXCLUDE_URL_PREFIXES': ['/excluded-path/'],
    'DIRECTIVES': CONTENT_SECURITY_POLICY_DIRECTIVES,
}


# OpenAI API Key
OPENAI_API_KEY = env.str('OPENAI_API_KEY', default=None)

# Error monitoring — a no-op unless a DSN is configured.
SENTRY_DSN = env.str('SENTRY_DSN', default=None)
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment='development' if DEBUG else 'production',
        send_default_pii=False,
        traces_sample_rate=env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.0),
    )
