"""Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.2.

Note: The doc reference URLs to djangoproject.com in project have been updated
to reflect the latest version of Django used in the project--currently 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import copy
import logging
import logging.config
import os
from pathlib import Path

from csp.constants import SELF
from django.utils.log import DEFAULT_LOGGING
from environs import Env

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'server': {  # Main app logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'server.apps': {  # Apps logger
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,  # Prevent propagation to avoid duplicate logs
        },
        'django': {  # Django framework logger
            'handlers': ['console'],
            'level': 'INFO',  # Set to INFO to reduce noise
            'propagate': True,
        },
    },
}

# Initialize logging
logging.config.dictConfig(LOGGING)
logger = logging.getLogger('server')

# Environment variables
# Reference: https://github.com/sloria/environs
env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def check_and_create_env_file():
    """Create a default .env file for local or production-like startup."""
    # NOTE: In production containers and gunicorn, the working directory is
    # the server project root. During local development from the repo root,
    # the server child directory is present.
    is_server_child_dir_present = (Path.cwd() / 'server').exists()
    if is_server_child_dir_present:
        env_file = 'server/.env'
    else:
        env_file = '.env'

    if not Path(env_file).is_file():
        logger.debug('Required .env file not found.')
        from django.core.management.utils import get_random_secret_key

        with open(env_file, 'a') as f:
            f.write('SECRET_KEY=' + get_random_secret_key() + '\n')
            if is_server_child_dir_present:
                f.write('DEBUG=True\n')
                f.write('DATABASE_URL=sqlite:///server/db.sqlite3\n')
                f.write('USE_LOCAL_FILE_STORAGE=True\n')
                f.write('MEDIA_ROOT=server/uploads\n')
                logger.debug(
                    'Created .env file at server/.env with default values for development.'
                )
                logger.warning('Please edit the .env file for production environment.')
            else:
                f.write('DEBUG=False\n')
                f.write('DATABASE_URL=sqlite:////data/db.sqlite3\n')
                f.write('MEDIA_ROOT=/data/uploads\n')
                logger.debug('Created .env file at .env with default values for production.')
        logger.debug('')


check_and_create_env_file()

env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start settings
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# Also https://fly.io/django-beats/deploying-django-to-production/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

FLY_APP_NAME = env('FLY_APP_NAME', default='')

if not DEBUG:
    ALLOWED_HOSTS = []
    if FLY_APP_NAME:
        ALLOWED_HOSTS.append(f'{FLY_APP_NAME}.fly.dev')
    ALLOWED_HOSTS += [
        '127.0.0.1',
        'localhost',
        'webframework.fly.dev',
        'webframework.dev',
        'wut.sh',
        'www.wut.sh',
    ]

    # HTTPS hardening for production behind the Fly proxy.
    # Fly terminates TLS at the edge and forwards the original scheme in
    # X-Forwarded-Proto; without this, request.is_secure() is always False
    # behind the proxy, so Secure cookies and HSTS would never apply.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HTTP->HTTPS redirection is handled at the edge (force_https in fly.toml),
    # so SECURE_SSL_REDIRECT stays off and internal health checks keep working.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The frontend reads the CSRF token from /auth/csrf/, not from the cookie.
    CSRF_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days; raise once proven stable

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    #
    # third-party apps
    'rest_framework',
    'corsheaders',
    'django_extensions',
    'django_tasks',
    'django_tasks_db',
    #
    # project apps
    'apps.users.apps.UsersConfig',
    'apps.website',
    'apps.blogs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.dj_db_url('DATABASE_URL', default='sqlite:///db.sqlite3')
    or {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    # The db_worker process polls and claims tasks in the same SQLite file;
    # WAL + busy timeout prevent "database is locked" errors.
    sqlite_options = DATABASES['default'].setdefault('OPTIONS', {})
    sqlite_options.setdefault(
        'init_command', 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;'
    )
    sqlite_options.setdefault('transaction_mode', 'IMMEDIATE')
    sqlite_options.setdefault('timeout', 20)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 16,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

SERVER_PATH = Path.cwd()
IS_SERVER_CHILD_DIR_PRESENT = (Path.cwd() / 'server').exists()
if IS_SERVER_CHILD_DIR_PRESENT:
    SERVER_PATH = SERVER_PATH / 'server'

STATIC_ROOT = SERVER_PATH / 'static'
STATIC_URL = '/static/'

if DEBUG:
    # Include static files from app/public directory during development
    # Reference: https://docs.djangoproject.com/en/5.1/ref/settings/#staticfiles-dirs
    STATICFILES_DIRS = [SERVER_PATH / '..' / 'app' / 'public']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/

LOGGING = copy.deepcopy(DEFAULT_LOGGING)


def setup_save_errorlog_to_file(logging: dict):
    """Configure server error logging to a rotating file."""
    import os

    log_dir: Path = BASE_DIR / '..' / 'log'
    errorlog_filepath: Path = log_dir / 'server-errors.log'

    def create_log_dir_for_server_errors():
        if not log_dir.exists():
            os.mkdir(log_dir)
        if not errorlog_filepath.exists():
            with open(errorlog_filepath, 'w'):
                pass

    create_log_dir_for_server_errors()

    # if not DEBUG:
    #     # In case of a single server managing multiple apps, symlink the
    #     # project's server error log to the common /var/log/app-errors directory.
    #     def symlink_error_log_in_system_logs():
    #         log_symlinkpath: str = f'/var/log/app-errors/{BASE_DIR.parent.name}.log'
    #         if not Path(log_symlinkpath).parent.exists():
    #             import subprocess

    #             subprocess.call('./sys/mkdir-error-log')
    #             # subprocess.call(BASE_DIR / '..' / 'sys/mkdir-error-log')
    #         if not Path(log_symlinkpath).is_symlink():
    #             os.symlink(errorlog_filepath, log_symlinkpath)

    #     try:
    #         symlink_error_log_in_system_logs()
    #     except FileNotFoundError as e:
    #         print(e)

    logging['handlers'].update(
        {
            'file_errors': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'formatter': 'django.server',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': errorlog_filepath,
                'maxBytes': 10485760,  # 10MB
                'backupCount': 5,
            },
        }
    )
    logging['loggers'].update(
        {
            'django': {
                'handlers': ['console', 'file_errors'],
                'level': 'INFO',
                'propagate': True,
            },
            'server': {
                'handlers': ['console', 'file_errors'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'server.apps': {
                'handlers': ['console', 'file_errors'],
                'level': 'DEBUG',
                'propagate': False,
            },
        }
    )
    return logging


LOGGING = setup_save_errorlog_to_file(LOGGING)


# User Model
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/
AUTH_USER_MODEL = 'users.User'


# REST Framework
# https://www.django-rest-framework.org/#example
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # Baseline abuse protection. Counters live in the default (local-memory)
    # cache, so rates are per process and approximate — good enough to blunt
    # bulk abuse, not a hard global guarantee.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/hour',
        'user': '1000/hour',
        'transcribe': '10/hour',
    },
}

# Background tasks (django-tasks, a backport of Django 6's django.tasks).
# Dev and CI run tasks inline so no worker process is needed; production uses
# the database backend, drained by `manage.py db_worker` (see server/start-prod.sh).
TASKS_IMMEDIATE = env.bool('TASKS_IMMEDIATE', default=DEBUG)
TASKS = {
    'default': {
        'BACKEND': (
            'django_tasks.backends.immediate.ImmediateBackend'
            if TASKS_IMMEDIATE
            else 'django_tasks_db.DatabaseBackend'
        ),
    }
}

# Handle server headers required for Cross-Origin Resource Sharing (CORS)
# https://pypi.org/project/django-cors-headers/
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    # 'http://localhost:8080',
]
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            'http://localhost:3000',
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ]
    )

CSRF_TRUSTED_ORIGINS = []
if FLY_APP_NAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{FLY_APP_NAME}.fly.dev')
CSRF_TRUSTED_ORIGINS += [
    'https://webframework.fly.dev',
    'https://webframework.dev',
    'https://wut.sh',
    'https://www.wut.sh',
]

# Set debug value in templates
# https://stackoverflow.com/questions/1271631/how-to-check-the-template-debug-flag-in-a-django-template
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']


# File storage configuration
USE_LOCAL_FILE_STORAGE = os.getenv('USE_LOCAL_FILE_STORAGE', 'False').lower() == 'true'

# S3-compatible object storage configuration
AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = f"https://{os.getenv('R2_ACCOUNT_ID')}.{os.getenv('R2_ENDPOINT_DOMAIN')}"
AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
AWS_S3_REGION_NAME = 'auto'  # R2 doesn't need a specific region
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False  # Don't add complex authentication-related query parameters to URLs
AWS_S3_ENDPOINT_FOR_CSP = os.getenv('R2_ENDPOINT_DOMAIN_FOR_CSP')

# Media files configuration
MEDIA_URL = env.str('MEDIA_URL', default='/media/')
MEDIA_ROOT = env.str('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'uploads'))
MAX_MEDIA_UPLOAD_BYTES = 100 * 1024 * 1024

# Storage backend configuration
STORAGES = {
    # https://whitenoise.readthedocs.io/en/stable/django.html
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    'default': {
        'BACKEND': (
            'django.core.files.storage.FileSystemStorage'
            if USE_LOCAL_FILE_STORAGE
            else 'storages.backends.s3boto3.S3Boto3Storage'
        ),
    },
}

# Create uploads directory if using local storage
if USE_LOCAL_FILE_STORAGE and not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)


# CSP settings
# Reference: https://django-csp.readthedocs.io/en/latest/configuration.html

CONTENT_SECURITY_POLICY_DIRECTIVES = {
    'default-src': [SELF],
    'frame-ancestors': [SELF],
    'form-action': [SELF],
    'report-uri': '/csp-report/',
    #
    'media-src': [SELF, 'blob:'],
    'img-src': [SELF, 'blob:'],
}

if DEBUG:
    from csp.constants import UNSAFE_INLINE

    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'script-src': [SELF, UNSAFE_INLINE],
            'script-src-elem': [
                SELF,
                UNSAFE_INLINE,
                'localhost:5173',
                'https://cdn.gpteng.co/gptengineer.js',
            ],
            'style-src': [SELF, UNSAFE_INLINE, 'http://localhost:5173/src/index.css'],
            'style-src-elem': [
                SELF,
                UNSAFE_INLINE,
                'http://localhost:5173/src/index.css',
            ],
            'connect-src': [SELF, 'http://localhost:8000', 'ws://localhost:5173'],
            'media-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('media-src', []),
                'https://citizen-dj.labs.loc.gov/audio/samplepacks/loc-fma/Mushrooms_fma-178531_001_00-00-01.mp3',
                'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            ],
            'img-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('img-src', []),
                'localhost:5173',
                'https://ui-avatars.com/api/',
            ],
        }
    )
else:
    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'script-src': [
                SELF,
                "'sha256-Ucm0AC6Vg7xQaBrSEjxBw5seBgXx38qp1ezaIVXWjWk='",
                #
                # Hashes for scripts in Django HTML templates
                "'sha256-DjsUj0pC5ySPg95mtQ6lmWjVIWW5WZ6Kta+NTTdw6FM='",
                "'sha256-dgKyP2HOH8aNvrK/3rkHdsaYbRTvken4D1lw/+6zP7c='",
            ],
            'style-src': [
                SELF,
                "'sha256-3FCgTKTk3allIr51SmmUMsCl5xih+z//3swOXTPQq6o='",
                "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
                "'sha256-7lAG9nNPimWNBky6j9qnn0jfFzu5wK96KOj/UzoG0hg='",
                "'sha256-CIxDM5jnsGiKqXs2v7NKCY5MzdR9gu6TtiMJrDw29AY='",
                "'sha256-9yCaDE0ZqnMqIHIqv/lrx+VJOh16ZKpxkH4PoBNWe2s='",
                "'sha256-nzTgYzXYDNe6BAHiiI7NNlfK8n/auuOAhh2t92YvuXo='",
                #
                # Hashes for styles in Django HTML templates
                "'sha256-GWweojyzwwt2WuqsMmaOTzMtCkOvLHnP8sc9dK1mDVo='",
                "'sha256-JayKhsDueQH1eSiZMpD2bwcA5rUMPYRclFLcblDmxvU='",
                "'sha256-c2svKMHHIytNvecMVUzr4RNy61AT1b0sYT937DFULOk='",
            ],
            'connect-src': [SELF, 'http://127.0.0.1:8000'],
        }
    )

if AWS_S3_ENDPOINT_FOR_CSP:
    CONTENT_SECURITY_POLICY_DIRECTIVES.update(
        {
            'connect-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('connect-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
            'media-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('media-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
            # Signed R2 URLs are used directly as <img src> for image posts.
            'img-src': [
                *CONTENT_SECURITY_POLICY_DIRECTIVES.get('img-src', []),
                AWS_S3_ENDPOINT_FOR_CSP,
            ],
        }
    )

CONTENT_SECURITY_POLICY = {
    # 'EXCLUDE_URL_PREFIXES': ['/excluded-path/'],
    'DIRECTIVES': CONTENT_SECURITY_POLICY_DIRECTIVES,
}


# OpenAI API Key
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
