# Generated by Django 5.1.5 on 2025-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
