# Generated by Django 5.1.5 on 2025-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_post_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_s3_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
