# Generated by Django 5.1.5 on 2025-04-07 20:38

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_audio_s3_file_key'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='audio',
        #     field=models.FileField(blank=True, null=True, upload_to=apps.blogs.models.audio_file_path),
        # ),
    ]
