# Generated by Django 5.1.5 on 2025-05-02 04:04

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_post_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='audio_s3_file_key',
            new_name='media_s3_file_key',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='audio',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='post',
            name='media_s3_file_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(
                blank=True, upload_to=apps.blogs.models.media_file_path
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='media_mp3',
            field=models.FileField(
                blank=True, upload_to=apps.blogs.models.media_file_path
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(
                blank=True,
                choices=[('audio', 'Audio'), ('video', 'Video')],
                max_length=255,
            ),
        ),
    ]
