# Generated by Django 5.1.5 on 2025-05-02 04:12

from django.db import migrations


def set_media_type(apps, schema_editor):
    Post = apps.get_model('blogs', 'Post')
    for post in Post.objects.all():
        if post.media:
            post.media_type = 'audio'
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_audio_s3_file_key_post_media_s3_file_key_and_more'),
    ]

    operations = [
        migrations.RunPython(set_media_type, migrations.RunPython.noop),
    ]
