# Generated by Django 5.1.5 on 2025-05-20 21:19

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_data_set_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to=apps.blogs.models.media_file_path)),
                (
                    'mp3_file',
                    models.FileField(
                        blank=True, upload_to=apps.blogs.models.media_file_path
                    ),
                ),
                ('s3_file_key', models.CharField(blank=True, max_length=255)),
                (
                    'media_type',
                    models.CharField(
                        choices=[('audio', 'Audio'), ('video', 'Video')], max_length=255
                    ),
                ),
                ('duration', models.DurationField(blank=True, null=True)),
                (
                    'thumbnail',
                    models.ImageField(
                        blank=True, upload_to=apps.blogs.models.media_file_path
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
