# Generated by Django 5.1.5 on 2025-06-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_link_media_to_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
