# Generated by Django 5.1.5 on 2025-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_media_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(
                choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')],
                max_length=255,
            ),
        ),
    ]
