# Generated by Django 5.1.5 on 2025-08-31 03:27

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_media_alt_text_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='compressed_file',
            field=models.ImageField(
                blank=True, upload_to=apps.blogs.models.media_file_path
            ),
        ),
        migrations.AddField(
            model_name='media',
            name='compressed_s3_file_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
