# Generated by Django 5.2.5 on 2026-07-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_comment_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(
                condition=models.Q(('s3_file_key', ''), _negated=True),
                fields=('s3_file_key',),
                name='unique_nonempty_s3_file_key',
            ),
        ),
    ]
