# Generated by Django 5.2.5 on 2026-07-07 19:06

"""Add transcript status to media rows."""

from django.db import migrations, models


def mark_existing_transcripts_done(apps, _schema_editor):
    """Mark media with existing transcript text as already transcribed."""
    media = apps.get_model('blogs', 'Media')
    media.objects.exclude(transcript='').update(transcript_status='done')


class Migration(migrations.Migration):
    """Add transcript status schema and backfill completed transcripts."""

    dependencies = [
        ('blogs', '0016_media_unique_nonempty_s3_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='transcript_status',
            field=models.CharField(
                blank=True,
                choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')],
                default='',
                max_length=16,
            ),
        ),
        migrations.RunPython(mark_existing_transcripts_done, migrations.RunPython.noop),
    ]
