# Generated by Django 5.2.5 on 2026-07-09

"""Add post privacy, drafts, and share tokens."""

from django.db import migrations, models

from apps.blogs.models import generate_share_token


def backfill_share_tokens(apps, _schema_editor):
    """Generate a distinct share token for each existing post."""
    post = apps.get_model('blogs', 'Post')
    for row in post.objects.only('id').iterator():
        row.share_token = generate_share_token()
        row.save(update_fields=['share_token'])


class Migration(migrations.Migration):
    """Add post visibility fields and backfill share tokens."""

    dependencies = [
        ('blogs', '0017_media_transcript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('public', 'Public'),
                    ('unlisted', 'Unlisted'),
                    ('private', 'Private'),
                ],
                db_index=True,
                default='public',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='share_token',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='share_token',
            field=models.CharField(default=generate_share_token, max_length=32),
        ),
    ]
