# Generated by Django 5.2.5 on 2026-07-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_post_privacy_and_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewer_key', models.CharField(max_length=64)),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='blogs.post',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('post', 'viewer_key'), name='unique_post_viewer'
                    )
                ],
            },
        ),
    ]
