# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
