# Generated by Django 5.2.5 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0020_post_pinned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='waveform',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
