# Generated by Django 5.2.5 on 2026-07-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_media_waveform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('youtube', 'YouTube'),
                            ('twitter', 'Twitter/X'),
                            ('generic', 'Generic'),
                        ],
                        default='generic',
                        max_length=16,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('ok', 'OK'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_handle', models.CharField(blank=True, max_length=100)),
                ('embed_id', models.CharField(blank=True, max_length=100)),
                (
                    'image',
                    models.ImageField(blank=True, upload_to='link_previews/%Y/%m/'),
                ),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='link_previews',
                        to='blogs.post',
                    ),
                ),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('post', 'url'), name='unique_post_link_url'
                    )
                ],
            },
        ),
    ]
