# Generated by Django 5.2.5 on 2026-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_linkpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpreview',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
