# Generated by Django 5.2.5 on 2026-07-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_linkpreview_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpreview',
            name='fetch_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='link_previews_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
