# Generated by Django 5.2.5 on 2026-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_linkpreview_fetch_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpreview',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='linkpreview',
            name='kind',
            field=models.CharField(
                choices=[
                    ('youtube', 'YouTube'),
                    ('twitter', 'Twitter/X'),
                    ('hackernews', 'Hacker News'),
                    ('reddit', 'Reddit'),
                    ('chatgpt', 'ChatGPT'),
                    ('generic', 'Generic'),
                ],
                default='generic',
                max_length=16,
            ),
        ),
    ]
