# Generated by Django 6.1 on 2026-08-13 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_linkpreview_extra_alter_linkpreview_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created', '-id'], name='blogs_post_feed_idx'),
        ),
    ]
