# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_alter_post_options_post_blogs_post_feed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client_uuid',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(
                condition=models.Q(('client_uuid__isnull', False)),
                fields=('author', 'client_uuid'),
                name='unique_author_client_uuid',
            ),
        ),
    ]
