"""Add the durable post client-request coordination ledger."""

# Generated by Django 6.1 on 2026-08-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create author-scoped UUID records shared by create and cancel."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0027_post_client_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostClientRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_uuid', models.UUIDField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('author', 'client_uuid'), name='unique_author_post_client_request'
                    )
                ],
            },
        ),
    ]
