# fly.toml app configuration file generated for web-framework-2025-lively-glitter-9000 on 2025-02-25T21:58:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'FLY_APP_NAME'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
