# Generated by Django 5.1.5 on 2025-02-26 00:27

from django.db import migrations
from django.contrib.auth import get_user_model

def create_anonymous_user(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username="anonymous").exists():
        User.objects.create(
            username="anonymous",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.RunPython(create_anonymous_user),
    ]
